# Generated by Django 3.1.1 on 2020-10-08 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('nombre', models.CharField(max_length=80, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=80)),
                ('nomusuario', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('contusuario', models.CharField(max_length=80)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CasoSemestral.tipousuario')),
            ],
        ),
    ]
