# Generated by Django 3.1.2 on 2020-10-29 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CasoSemestral', '0003_auto_20201022_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenGaleria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='galeria')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagenSlider', models.ImageField(upload_to='slider')),
            ],
        ),
    ]
