# Generated by Django 3.1.2 on 2020-10-29 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CasoSemestral', '0004_imagengaleria_imagenslider'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuienesSomos',
            fields=[
                ('ident', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('mision', models.TextField()),
                ('vision', models.TextField()),
            ],
        ),
    ]
